version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_algafood
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algafood
      MYSQL_USER: algauser
      MYSQL_PASSWORD: algapass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
